public record CarResource(
    int Id,
    string Title,
    string Owner,
    string OwnerEmail,
    int Year,
    int BrandId,
    string Brand,
    string Model,
    string? Description,
    string? ImageUrl,
    decimal Price,
    string LicensePlate,
    int OriginalReservationId,
    bool HasPdfCertification,
    DateTime CreatedAt,
    DateTime CertificateExpirationDate,
    bool IsCertificateValid,
    string? CertificateSignature
);
