services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: certiweb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - certiweb-network

  api:
    image: "svennn/certiweb-api:latest"
    ports:
      - "3000:8080"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;User Id=postgres;Password=postgres;Database=certiweb
    networks:
      - certiweb-network

  api2:
    image: "svennn/certiweb-api:latest"
    ports:
      - "3001:8080"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;User Id=postgres;Password=postgres;Database=certiweb
    networks:
      - certiweb-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - api2
    networks:
      - certiweb-network

  frontend:
    image: "svennn/certiweb-frontend:latest"
    ports:
      - "5173:80"
    depends_on:
      - nginx
    environment:
      - VITE_SERVER_BASE_PATH=http://nginx:80/api/v1
    networks:
      - certiweb-network

volumes:
  postgres_data:

networks:
  certiweb-network:
    driver: bridge